### ISSUE TITLE
Chart won't re render on data state update

### ISSUE THREAD

**Issue by prajwolshrestha** [eunchurn/components#98]
Hi there,

The chart seem to load as expected on load.

But when the data state is updated with a ajax response, chart doesn't re render?

Does the chart not have the reactive functionality or am I missing something?

Any pointers would highly appreciated.

TIA.

**Comment by prajwolshrestha** [comment]
Here's the part file I've been working on.

`
import useRoute from "@/Hooks/useRoute";
import axios, { AxiosResponse } from "axios";
import React, { useEffect, useState } from "react";

import { Chart, calculateWindRose } from "@eunchurn/react-windrose";

interface WindDirectionChartProps {
    title: string;
    daterange: Date[];
    filterType: string;
}

export default function WindDirectionChart({ daterange, title, filterType }: WindDirectionChartProps): JSX.Element {
    const [data, setData] = useState<any[]>([]);
    const route = useRoute();

    const chart_data: any[] = [{
        direction: [],
        speed: []
    }];

    useEffect(() => {
        if (daterange.length > 0) {
            axios.get(
                route('reports.wind_direction'),
                {
                    params: {
                        start_date: daterange[0],
                        end_date: daterange[1],
                        filter_type: filterType
                    }
                }).then((response: AxiosResponse) => {
                    setData(response.data);
                });
        }
    }, [daterange]);

    if (data.length) {
        data.map(obj => {
            if (obj.wind_direction != null && obj.wind_speed != null) {
                chart_data[0].direction.push(obj.wind_direction);
                chart_data[0].speed.push(obj.wind_speed);
            }
        });

        const windRoseData = {
            data: calculateWindRose(chart_data[0]),
            columns: ["angle", "0-1", "1-2", "2-3", "3-4", "4-5", "5-6", "6-7", "7+"]
        }

        return (
            <Chart
                chartData={windRoseData.data}
                columns={windRoseData.columns}
                responsive={false}
                width={800}
                height={500}
            />
        );

    } else {
        return (
            <></>
        );
    }
}

`

**Comment by prajwolshrestha** [comment]
I have attached the file.

Could you please see where did I go wrong?

[WindDirectionChart.tsx.txt](https://github.com/eunchurn/components/files/14414898/WindDirectionChart.tsx.txt)

**Comment by eunchurn** [comment]
Hi @prajwolshrestha, it was a bug. Please update your `package.json` "@eunchurn/react-windrose": "1.3.1"`.

Check this example <https://stackblitz.com/edit/nextjs-react-windrose-chart>
